FROM python:3.11-slim

WORKDIR /app

# Copy requirements first to leverage Docker cache
COPY frontend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY frontend/ ./frontend

# Expose port
EXPOSE 10000

# Start server
CMD ["sh", "-c", "cd frontend && export BACKEND_URL=https://$RAILWAY_SERVICE_NAME-qrng-backend.up.railway.app && python run.py"]